# Generated by Django 5.2.3 on 2025-07-22 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('destinatario', models.EmailField(max_length=254)),
                ('asunto', models.TextField(max_length=100)),
                ('mensaje', models.TextField(max_length=1000)),
                ('archivo', models.FileField(blank=True, upload_to='archivos/')),
                ('factura', models.FileField(blank=True, upload_to='facturas/')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
